// Code generated by goctl. DO NOT EDIT.
// Source: Mercury.proto

package server

import (
	"context"

	"Mercury/app/Mercury-web/rpc/internal/logic"
	"Mercury/app/Mercury-web/rpc/internal/svc"
	"Mercury/app/Mercury-web/rpc/mercury"
)

type MercuryServer struct {
	svcCtx *svc.ServiceContext
	mercury.UnimplementedMercuryServer
}

func NewMercuryServer(svcCtx *svc.ServiceContext) *MercuryServer {
	return &MercuryServer{
		svcCtx: svcCtx,
	}
}

func (s *MercuryServer) Send(ctx context.Context, in *mercury.SendRequest) (*mercury.SendResponse, error) {
	l := logic.NewSendLogic(ctx, s.svcCtx)
	return l.Send(in)
}

func (s *MercuryServer) BatchSend(ctx context.Context, in *mercury.BatchSendRequest) (*mercury.SendResponse, error) {
	l := logic.NewBatchSendLogic(ctx, s.svcCtx)
	return l.BatchSend(in)
}
